version: 0.2

phases:
  build:
    commands:
      - echo "========================================="
      - echo "STAGE 1: BUILD (Docker Build)"
      - echo "========================================="
      - echo "Building the Docker image..."
      - cd apps
      - docker build -t simple-app:latest .
      - cd ..

artifacts:
  files:
    - '**/*'
  base-directory: apps
