version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install SonarScanner CLI (Pre-requisite for CodeBuild)
      - |
        if [ "$PIPELINE_STAGE" = "TEST" ]; then
          echo "Downloading SonarScanner..."
          export SONAR_SCANNER_VERSION=5.0.1.3006
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
          unzip -q $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        fi
      - export PATH=$HOME/.sonar/sonar-scanner-5.0.1.3006-linux/bin:$PATH
      
      # =========================================
      # STAGE: Build
      # =========================================
      - echo "--- STAGE BUILD ---"
      - cd apps
      - npm install
      - cd ..

  pre_build:
    commands:
      # =========================================
      # STAGE: Testing
      # =========================================
      - |
        if [ "$PIPELINE_STAGE" = "TEST" ]; then
          echo "--- STAGE TESTING ---"
          cd apps
          npm test
          npm run test:coverage || echo "Tests failed, continuing for Sonar"
          cd ..
        fi

  build:
    commands:
      # =========================================
      # STAGE: Code Review
      # =========================================
      - |
        if [ "$PIPELINE_STAGE" = "TEST" ]; then
          echo "--- STAGE CODE REVIEW ---"
          sonar-scanner -Dsonar.projectKey=Simple-Apps -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
        fi

artifacts:
  files:
    - '**/*'
  base-directory: apps
